# Generated by Django 6.0.2 on 2026-06-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="priority",
            field=models.CharField(
                choices=[
                    ("ADHERENT", "Adherent"),
                    ("ROBOTECH", "Robotech"),
                    ("AUTOTECH", "Autotech"),
                    ("DRONE", "Drone"),
                    ("BUREAU", "Bureau"),
                ],
                default="ADHERENT",
                max_length=25,
            ),
        ),
    ]
