# Generated by Django 6.0.2 on 2026-08-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_priority_user_role_user_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="status",
            field=models.CharField(
                choices=[
                    ("SUBMITTED", "Submitted"),
                    ("AWAITING_PAYMENT", "Awaiting Payment"),
                    ("PENDING", "Pending"),
                    ("PRINTING", "Printing"),
                    ("AWAITING_PICKUP", "Awaiting Pickup"),
                    ("PICKED_UP", "Picked Up"),
                    ("FAILED", "Failed"),
                    ("REFUNDED", "Refunded"),
                    ("CANCELED", "Canceled"),
                ],
                default="SUBMITTED",
                max_length=25,
            ),
        ),
    ]
