# Generated by Codex security hardening.

from django.db import migrations, models
from django.db.models.functions import Lower


def normalize_user_emails(apps, schema_editor):
    User = apps.get_model('api', 'User')
    seen = {}
    for user in User.objects.all().order_by('id'):
        normalized = (user.email or '').strip().lower()
        if not normalized:
            continue
        existing_id = seen.get(normalized)
        if existing_id is not None:
            raise ValueError(
                f'Duplicate email after lower-case normalization: {normalized!r} '
                f'for users {existing_id} and {user.pk}'
            )
        seen[normalized] = user.pk
        if normalized != user.email:
            user.email = normalized
            user.save(update_fields=['email'])


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_request_status'),
    ]

    operations = [
        migrations.RunPython(normalize_user_emails, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(Lower('email'), name='api_user_email_lower_unique'),
        ),
    ]
