# Generated by Codex security hardening.

import uuid

import django.db.models.deletion
from django.db import migrations, models


def prepare_integrity_constraints(apps, schema_editor):
    User = apps.get_model('api', 'User')
    Filament = apps.get_model('api', 'Filament')
    Operation = apps.get_model('api', 'Operation')

    negative_credit_ids = list(
        User.objects.filter(credit__lt=0).values_list('pk', flat=True)[:10]
    )
    if negative_credit_ids:
        raise ValueError(f'Cannot add non-negative credit constraint; negative users: {negative_credit_ids}')

    Filament.objects.filter(price__lt=1).update(price=1)

    duplicates = []
    for operation_type in ('PAYMENT', 'REFUND'):
        rows = (
            Operation.objects
            .filter(operation_type=operation_type, request__isnull=False)
            .values('request_id')
            .annotate(count=models.Count('id'))
            .filter(count__gt=1)
        )
        duplicates.extend((operation_type, row['request_id'], row['count']) for row in rows)
    if duplicates:
        raise ValueError(f'Cannot add operation idempotency constraints; duplicates: {duplicates[:10]}')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_email_case_insensitive'),
    ]

    operations = [
        migrations.RunPython(prepare_integrity_constraints, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='filament',
            name='price',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='file',
            name='filament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.filament'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operation_agent', to='api.user'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='beneficiary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operation_beneficiary', to='api.user'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.request'),
        ),
        migrations.AlterField(
            model_name='request',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.file'),
        ),
        migrations.AlterField(
            model_name='request',
            name='printer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.printer'),
        ),
        migrations.AlterField(
            model_name='request',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.user'),
        ),
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=80)),
                ('target_type', models.CharField(max_length=120)),
                ('target_id', models.CharField(max_length=120)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_action_logs', to='api.user')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('credit__gte', 0)), name='api_user_credit_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='filament',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 1)), name='api_filament_price_positive'),
        ),
        migrations.AddConstraint(
            model_name='operation',
            constraint=models.UniqueConstraint(condition=models.Q(('operation_type', 'PAYMENT'), ('request__isnull', False)), fields=('request',), name='api_operation_one_payment_per_request'),
        ),
        migrations.AddConstraint(
            model_name='operation',
            constraint=models.UniqueConstraint(condition=models.Q(('operation_type', 'REFUND'), ('request__isnull', False)), fields=('request',), name='api_operation_one_refund_per_request'),
        ),
    ]
