# Generated by Django 6.0.2 on 2026-04-04 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="request",
            old_name="file_id",
            new_name="file",
        ),
        migrations.RemoveField(
            model_name="file",
            name="user_id",
        ),
        migrations.AddField(
            model_name="request",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="request",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="printer",
            name="type",
            field=models.CharField(
                choices=[
                    ("CREALITY_K1C", "Creality K1C"),
                    ("SNAPMAKER_U1", "Snapmaker U1"),
                    ("PRUSA_MK3", "Prusa Mk3"),
                ],
                max_length=25,
            ),
        ),
        migrations.AlterField(
            model_name="request",
            name="status",
            field=models.CharField(
                choices=[
                    ("SUBMITTED", "Submitted"),
                    ("AWAITING_PAYMENT", "Awaiting Payment"),
                    ("PENDING", "Pending"),
                    ("PRINTING", "Printing"),
                    ("AWAITING_PICKUP", "Awaiting Pickup"),
                    ("PICKED_UP", "Picked Up"),
                    ("FAILED", "Failed"),
                    ("CANCELED", "Canceled"),
                ],
                default="PENDING",
                max_length=25,
            ),
        ),
    ]
