# Generated by Django 6.0.2 on 2026-04-04 21:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_file_id_request_file_remove_file_user_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="request",
            old_name="printer_id",
            new_name="printer",
        ),
        migrations.AlterField(
            model_name="request",
            name="file",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.file"
            ),
        ),
    ]
