# Generated by Django 6.0.2 on 2026-06-06 12:59

import back.apps.api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_user_priority"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="priority",
            new_name="role",
        ),
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=back.apps.api.models.User.profile_pic_path,
            ),
        ),
    ]
