# Generated by Django 6.0.2 on 2026-04-04 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_printer_id_request_printer_alter_request_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="filament_id",
        ),
        migrations.AddField(
            model_name="file",
            name="filament",
            field=models.ManyToManyField(null=True, to="api.filament"),
        ),
    ]
