# Generated by Django 6.0.2 on 2026-04-04 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_file_filament_id_file_filament"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="file",
            name="filament",
        ),
        migrations.AddField(
            model_name="file",
            name="filament",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.filament",
            ),
        ),
    ]
