# Generated by Django 6.0.2 on 2026-04-05 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_remove_file_filament_file_filament"),
    ]

    operations = [
        migrations.AddField(
            model_name="operation",
            name="request",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.request"
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="operation_type",
            field=models.CharField(
                choices=[("CASH", "Cash"), ("CARD", "Card"), ("PAYMENT", "Payment")],
                max_length=25,
            ),
        ),
    ]
