# Generated by Django 6.0.2 on 2026-04-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_operation_request_alter_operation_operation_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="operation",
            old_name="agent_id",
            new_name="agent",
        ),
        migrations.RenameField(
            model_name="operation",
            old_name="beneficiary_id",
            new_name="beneficiary",
        ),
        migrations.AlterField(
            model_name="operation",
            name="operation_type",
            field=models.CharField(
                choices=[
                    ("CASH", "Cash"),
                    ("CARD", "Card"),
                    ("PAYMENT", "Payment"),
                    ("REFUND", "Refund"),
                ],
                max_length=25,
            ),
        ),
    ]
