# Generated by Django 6.0.2 on 2026-04-05 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_rename_agent_id_operation_agent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filament",
            name="type",
            field=models.CharField(
                choices=[("PLA", "Pla"), ("PETG", "Petg")], max_length=25
            ),
        ),
        migrations.AlterField(
            model_name="operation",
            name="request",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="api.request"
            ),
        ),
    ]
