# Generated by Django 6.0.2 on 2026-04-05 20:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_alter_filament_type_alter_operation_request"),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE api_request DROP CONSTRAINT IF EXISTS api_request_printer_id_27fa4698_fk_api_printer_id;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RemoveField(
            model_name="filament",
            name="colour",
        ),
        migrations.RemoveField(
            model_name="printer",
            name="id",
        ),
        migrations.RemoveField(
            model_name="printer",
            name="type",
        ),
        migrations.AddField(
            model_name="filament",
            name="color",
            field=models.CharField(
                default="#ffffff",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        "^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$"
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="filament",
            name="color_name",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="printer",
            name="name",
            field=models.CharField(
                choices=[
                    ("CREALITY_K1C", "Creality K1C"),
                    ("SNAPMAKER_U1", "Snapmaker U1"),
                    ("PRUSA_MK3", "Prusa Mk3"),
                ],
                default=1,
                max_length=25,
                primary_key=True,
                serialize=False,
            ),
            preserve_default=False,
        ),
    ]
