# Generated by Django 6.0.2 on 2026-06-05 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_priority'),
        ('api', '0009_remove_filament_colour_remove_printer_id_and_more'),
    ]

    operations = [
    ]
