@startuml
title "  Diagramme UML \n Base de données"

' --- STYLE ---
hide circle
skinparam linetype ortho
skinparam shadowing false
skinparam roundcorner 10

' --- ENTITÉS ---
entity "User" as user {
  *id : UUID <<PK>>
  --
  *email : varchar(254) <<UNIQUE>>
  credit : numeric(6,2) = 0
}
class "AbstractUser" as abstract_user {
        username
        password
        is_staff
        is_superuser
        ...
    }
entity "Printer" as printer {
        *id : UUID <<PK>>
        type : varchar(25)
        status : varchar(25)
}

' --- RELATIONS ---
' ||-- = One (Obligatoire)
' }o-- = Many (Optionnel)

abstract_user <|-- user : Inherit

@enduml