@startuml
title "  Diagramme UML \n Base de données"

' --- STYLE ---
hide circle
skinparam linetype ortho
skinparam shadowing false
skinparam roundcorner 10

' --- ENTITÉS ---
' On définit une entité avec ses champs
entity "User" as user {
  *id : UUID <<PK>>
  --
  *email : varchar(254) <<UNIQUE>>
  password_hash : text
  created_at : timestamp
}

entity "Commande" as order {
  *id : UUID <<PK>>
  --
  *user_id : UUID <<FK>>
  total_price : decimal
  status : enum
}

entity "Ligne_Commande" as order_line {
  *id : UUID <<PK>>
  --
  *order_id : UUID <<FK>>
  product_id : UUID
  quantity : int
}

' --- RELATIONS ---
' ||-- = One (Obligatoire)
' }o-- = Many (Optionnel)

user ||..o{ order : "Passe"
order ||--|{ order_line : "Contient"

@enduml